### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Benceplays** [Benceplays/kosarphp#1]
- [ ] játékos csere
- [x] játékos csere kiirása eventbe
- [x] letiltani a funkciókat ha vége
- [x] letiltani a funkciókat ha szünetel
- [x] valami kis hint h ki készítette
- [x] le maximalizálni h 5 játékos lehet csak
- [x] mezszám kiiratása

**Comment by Benceplays** [comment]
azoknak a játékosoknak akik cserélve lettek hozzá kéne adni egyet az indexéhez, és valamiért nem kapja meg a játékos indexét és azért van az hogy 6 jatekos lesz a teamnel
